"""Diputies table name update

Revision ID: 381578e3635a
Revises: ca45ae5f70f7
Create Date: 2020-08-15 21:52:47.231959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '381578e3635a'
down_revision = 'ca45ae5f70f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diputies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'lastname')
    )
    op.drop_index('name', table_name='diputy')
    op.drop_table('diputy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diputy',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('birth_date', mysql.DATETIME(), nullable=True),
    sa.Column('dni', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'diputy', ['name', 'lastname'], unique=True)
    op.drop_table('diputies')
    # ### end Alembic commands ###
